### ISSUE TITLE
Create a GitHub action to be used per plugin

### ISSUE THREAD

**Issue by carstingaxion** [prjblk/wordpress-audit-automation#1]
Hello @eddiez9 ,

I would have a loved to leave a comment on your blog post, in the absence of a comment form, I allow myself to go that way. 

You wrote a great post with a lot to learn, Thank you!

Can you imagine creating a GitHub actions workflow out of it, to make it even better re-usable?

I’m asking not for a personal profit project or my work, I’m asking for a WordPress community project called [GatherPress](https://github.com/GatherPress/gatherpress). We would love to have some additional automation in place, that’ll prevent the plugin (-team) from the most obvious problems.

**Comment by eddiez9** [comment]
Hey @carstingaxion,

Thanks for your kind words! 

If you're interested in running Semgrep OSS as a part of your workflows, they publish sample Github Actions here that you could incorporate: https://semgrep.dev/docs/semgrep-ci/sample-ci-configs
